*Auteur : Valentin Mathieu - Dernière mise à jour 02 Septembre 2024*

***

# Liens utiles pour R

<!-- :240903:gf:r:enseignement: -->

## First rule of the coding club: you do not talk about the Coding Club

Une série de tutoriels extrêmement bien faits, et sur lesquels ce cours s'appuie largement, provient du travail du Coding Club.
Ils sont à retrouver [ici](https://ourcodingclub.github.io/tutorials.html).
Ne pas hésiter à y jeter un coup d'œil pour explorer davantage ou simplement se remémorer des procédures.

Pour des tutoriels en français sur l'utilisation de R pour l'analyse de données, le GOAT R de France reste François Hussons. 
Son site propose de nombreux tutoriels. 
Il faut fouiller un peu mais c'est un excellent niveau et avec un soucis de la pédagogie certain.
Ses tutoriels sont disponibles [ici](https://husson.github.io/tutorials.html).
Les livres qu'il a écrit [ici](https://husson.github.io/books.html).
Les MOOC qu'il a créé [ici](https://husson.github.io/MOOC.html).

## Introduction à R 

Pour s'initier à R :

- [Introduction à R, vecteurs, dataframe et matrices](http://tryr.codeschool.com)
- [Une collection de codes R allant des bases à la visualisation de données et aux statistiques](http://sthda.com)
- [Un guide en ligne complet sur l'utilisation de R](http://www.cookbook-r.com/)
- [Un métablog de tutoriels R](http://www.r-bloggers.com)
- [Vidéos d'un cours en ligne sur R (introduction à R, formatage des données, visualisation des données)](http://blog.revolutionanalytics.com/2012/12/coursera-videos.html)
- [Comment citer R et les packages R dans votre travail](http://www.blopig.com/blog/2013/07/citing-r-packages-in-your-thesispaperassignments/)

## Graphique et visualisation des données

- [Base Graphics in R : A Detailed Idiot's Guide](susanejohnston.wordpress.com/2013/08/30/base-graphics-in-r-a-detailed-idiots-guide/)
- [Exemples de chapitres du livre ggplot2 de Hadley Wickham](ggplot2-book.org/)
- [Valeurs de couleur R](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf)
- [Guide graphique, principalement ggplot2](ase.tufts.edu/bugs/guide/assets/R%20Graphics%20Cookbook.pdf)
- [Tutoriels Shiny](shiny.rstudio.com)

## R Markdown, contrôle de version, analyse reproduction

- [Introduction à la recherche reproductible dans R et RStudio](susanejohnston.wordpress.com/2015/05/12/an-introduction-to-reproducible-research-in-r-and-r-studio/)
- [Télécharger LaTeX, trouver des tutoriels et des guides utiles](www.latex-project.org)
- [Dépôt de tutoriels Github](help.github.com/articles/good-resources-for-learning-git-and-github/)
- [Fiche de contrôle Markdown](github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet)
- [Vidéo d'introduction aux carnets de notes R](www.rstudio.com/resources/webinars/introducing-notebooks-with-r-markdown/)
- [Guide concis de la programmation LaTeX](https://tobi.oetiker.ch/lshort/lshort.pdf)
- [British Ecological Society Guide to Data Management in Ecology and Evolution](britishecologicalsociety.org/wp-content/uploads/Publ_Data-Management-Booklet.pdf)
- [Matériel pour les ateliers sur le contrôle des versions et le code reproductible lors de la réunion annuelle 2016 de la British Ecological Society](github.com/BES2016Workshop)

## Analyse statistique 

En plus des [tutoriels de François Husson](https://husson.github.io/tutorials.html) :

- [Manuel standard de statistiques biologiques utilisant R](rcompanion.org/documents/RCompanionBioStatistics.pdf)
- [Le livre R for Data Science de Hadley Wickham](r4ds.had.co.nz/)

## Manipulation des données

- [Voir la théorie : un guide visuel étonnant pour les statistiques](students.brown.edu/seeing-theory/index.html)
- [Le package dplyr et les pipes](seananderson.ca/2014/09/13/dplyr-intro.html)
- [Feuille de contrôle pour le traitement des données, dplyr et tidyr](www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
- [Cheatsheets pour ggplot, dplyr, Shiny, etc.](www.rstudio.com/resources/cheatsheets/)

## Shiny 

[Le tutoriel officiel Shiny de RStudio](http://shiny.rstudio.com/tutorial/)

## Dépannage

[Poser des questions.](stackoverflow.com)

***